# Generated by Django 4.2.3 on 2023-08-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drfapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
